name: Build WebView APK

on:
  workflow_dispatch:
    inputs:
      site_url:
        description: 'Website URL for WebView'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Set up Gradle 7.6
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 7.6

      - name: List Gradle tasks (optional)
        run: |
          cd webview-app
          gradle tasks

      - name: Build APK with site_url
        run: |
          cd webview-app
          gradle :app:assembleDebug -Psite_url="${{ github.event.inputs.site_url }}"

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: WebView-APK
          path: webview-app/app/build/outputs/apk/debug/*.apk
