name: Build WebView APK

on:
  workflow_dispatch:
    inputs:
      site_url:
        required: true
        type: string
      app_name:
        required: true
        type: string
      logo_url:
        required: true
        type: string
      account_id:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 11

      - name: Download logo
        run: |
          curl -L "${{ inputs.logo_url }}" -o app/src/main/res/mipmap-xxxhdpi/ic_launcher.png

      - name: Set app name
        run: |
          sed -i "s|<string name=\"app_name\">.*</string>|<string name=\"app_name\">${{ inputs.app_name }}</string>|" app/src/main/res/values/strings.xml

      - name: Inject site URL
        run: |
          echo "buildConfigField \"String\", \"SITE_URL\", \\\"${{ inputs.site_url }}\\\"" >> app/build.gradle

      - name: Build APK
        run: ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.account_id }}-webview-app
          path: app/build/outputs/apk/release/app-release.apk
