name: Build WebView APK (Release Build)

on:
  workflow_dispatch:
    inputs:
      site_url:
        required: true
        type: string
      app_name:
        required: true
        type: string
      logo_url:
        required: true
        type: string
      account_id:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 7.6

      - name: Verify keystore file exists
        run: |
          ls -l webview-app/app/keystore/release-key.jks

      - name: Check keystore credentials
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          echo "Checking keystore info..."
          keytool -list -v -keystore webview-app/app/keystore/release-key.jks \
            -storepass "$KEYSTORE_PASSWORD" \
            -alias "$KEY_ALIAS"

      - name: Ensure logo folder exists
        run: mkdir -p webview-app/app/src/main/res/mipmap-xxxhdpi

      - name: Download logo
        run: |
          curl -L "${{ inputs.logo_url }}" -o webview-app/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png

      - name: Set app name in strings.xml
        run: |
          sed -i "s|<string name=\"app_name\">.*</string>|<string name=\"app_name\">${{ inputs.app_name }}</string>|" webview-app/app/src/main/res/values/strings.xml

      - name: Replace site URL in strings.xml
        run: |
          sed -i "s|https://defaultsite.com|${{ inputs.site_url }}|" webview-app/app/src/main/res/values/strings.xml

      - name: Build APK (Online Gradle)
        run: |
          cd webview-app
          gradle assembleRelease

      - name: List APK files before upload
        run: |
          ls -l webview-app/app/build/outputs/apk/release/

      - name: Upload Release APK to PHP server
        run: |
          curl -X POST \
            -F "apk_file=@webview-app/app/build/outputs/apk/release/app-release.apk" \
            -F "account_id=${{ inputs.account_id }}" \
            -F "app_name=${{ inputs.app_name }}" \
            https://activespreadsheet.com/upload.php
