name: Build WebView APK

on:
  workflow_dispatch:
    inputs:
      site_url:
        required: true
        type: string
      app_name:
        required: true
        type: string
      logo_url:
        required: true
        type: string
      account_id:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin

      - name: Set up Gradle 7.6
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 7.6

      - name: Ensure logo folder exists
        run: mkdir -p webview-app/app/src/main/res/mipmap-xxxhdpi

      - name: Download logo
        run: |
          curl -L "${{ inputs.logo_url }}" -o webview-app/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png

      - name: Set app name
        run: |
          sed -i "s|<string name=\"app_name\">.*</string>|<string name=\"app_name\">${{ inputs.app_name }}</string>|" webview-app/app/src/main/res/values/strings.xml

      - name: Build APK
        run: |
          cd webview-app
          gradle assembleRelease -Psite_url="${{ inputs.site_url }}"

      - name: Verify APK build output
        run: |
          find webview-app/app/build/outputs/apk/release

      - name: Rename APK to app name
        run: |
          mv webview-app/app/build/outputs/apk/release/app-release.apk \
             webview-app/app/build/outputs/apk/release/${{ inputs.app_name }}.apk

      - name: Upload APK to PHP server
        run: |
          curl -X POST \
            -F "apk_file=@webview-app/app/build/outputs/apk/release/${{ inputs.app_name }}.apk" \
            -F "account_id=${{ inputs.account_id }}" \
            -F "app_name=${{ inputs.app_name }}" \
            https://activespreadsheet.com/upload.php
