name: Build WebView APK

on:
  workflow_dispatch:
    inputs:
      logo_url:
        description: 'Logo URL (PNG)'
        required: true
      site_url:
        description: 'Website URL for WebView'
        required: true
      app_name:
        description: 'App Name for the APK'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Set up Gradle 7.6
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 7.6

      - name: List Gradle tasks (optional)
        run: |
          cd webview-app
          gradle tasks

      - name: Download and replace logo icon
        run: |
          cd webview-app
          for density in mdpi hdpi xhdpi xxhdpi xxxhdpi; do
            mkdir -p app/src/main/res/mipmap-$density
            curl -L "${{ github.event.inputs.logo_url }}" -o app/src/main/res/mipmap-$density/ic_launcher.png || echo "Logo download failed for $density"
          done

      - name: Build APK with site_url and app_name
        run: |
          cd webview-app
          gradle :app:assembleDebug \
            -Psite_url="${{ github.event.inputs.site_url }}" \
            -Papp_name="${{ github.event.inputs.app_name }}"

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: WebView-APK
          path: webview-app/app/build/outputs/apk/debug/*.apk
