name: Build WebView APK

on:
  workflow_dispatch:
    inputs:
      site_url:
        description: 'Website URL for WebView'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Java (required for Gradle and Android builds)
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      # Step 3: Set up Gradle 7.6 system-wide (not using gradle wrapper)
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 7.6

      # Step 4: List Gradle tasks (Optional, useful for debugging)
      - name: List Gradle tasks
        run: |
          cd webview-app
          gradle tasks

      # Step 5: Build the APK inside the 'webview-app' folder, injecting 'site_url' input
      - name: Build APK with site_url
        run: |
          cd webview-app
          gradle assembleDebug -Psite_url="${{ github.event.inputs.site_url }}"

      # Step 6: Upload the generated APK as a workflow artifact
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: WebView-APK
          path: webview-app/app/build/outputs/apk/debug/*.apk
